### ISSUE TITLE
Replace Select/Deselect keywords with Checkboxes for projects in "Create Collection"

### ISSUE THREAD

**Issue by 24santoshr** [ABenchM/abm-frontend#10]
Using checkboxes for select/ deselect operations instead of select/deselect keywords for projects and making the projects 'checked/unchecked' by clicking these checkboxes.

**Comment by ankur-1989** [comment]
@nguyenLisa This functionality of select deselect buttons still need to be put in abm-frontend. I was thinking if we have to replace those buttons by checkboxes then I will directly use check-box instead of buttons. what do you suggest?

**Comment by nguyenLisa** [comment]
@ankur-1989  I agree with that.

**Comment by ankur-1989** [comment]
Implemented and pushed to develop branch.Closing this issue.
