### ISSUE TITLE
Inconsistent behaviour of pinned collections on the 'Public Collections' page

### ISSUE THREAD

**Issue by johannesduesing** [ABenchM/abm-frontend#12]
Adding a public collection to the users pinned collections adds an entry with that collection containing a button 'Unpin' to the 'Pinned Collections'-Tab. When searching for the same collection again afterwards, it will show up as search result containing the button 'Pin', not 'Unpin'. Clicking the button 'Pin' (while the collection already is pinned) will yield a message 'Failed with [500] server error'.

How to reproduce:
1.  Search for a public collection and click its 'Pin'-Button. ( The collection will be removed from the search results and added to the 'Pinned Collections'-Tab. )
2.  Search for the same public collection again. ( It will show up with a 'Pin'-Button in the search results. )
3. Click the 'Pin'-Button in the search results. ( An error message will be displayed. )

On top of that, if a pinned collection is unpinned, it will not show up in the public collections search until the page is refreshed.

How to reproduce:
1. Unpin a pinned collection
2. Search for that collection in the public collections

**Comment by johannesduesing** [comment]
This is related to the issues 114 and 109 in the abm repository 

- https://github.com/ABenchM/abm/issues/114
- https://github.com/ABenchM/abm/issues/109

**Comment by ankur-1989** [comment]
@johannesduesing  These issues have been fixed in abm-frontend and changes are already there in develop branch. Please feel free to test the same and let me know if you still find something.

**Comment by ankur-1989** [comment]
Closing this issue. Implemented and pushed to Github.
