### ISSUE TITLE
Provide a functionality to unfreeze the built collection.

### ISSUE THREAD

**Issue by ankur-1989** [ABenchM/abm-frontend#123]

**Comment by nguyenLisa** [comment]
No need to freeze now, since we have the public-private system.

**Comment by ankur-1989** [comment]
ok. As of now, by unfreezing the version we can rebuild it if we want. Do we need to keep the rebuilding feature instead of this?

**Comment by nguyenLisa** [comment]
One can derive a new version from a public version. This is the equivalent of unfreezing and we don't need this freeze/unfreeze system anymore.

**Comment by ankur-1989** [comment]
ok sure. I'll remove this feature and close this request.

**Comment by ankur-1989** [comment]
This feature is not needed anymore. Therefore, closing this issue.
