### ISSUE TITLE
Add a page number on the "Select a commit"-Frame in the "Create Collection" page

### ISSUE THREAD

**Issue by johannesduesing** [ABenchM/abm-frontend#13]
By now, there are 'Previous' and 'Next'-Page Buttons on the "Select a commit"-Frame, but no indication of the current page number or the overall number of pages. Even the 'Previous' Button is enabled when the User is on the first page. 

To make navigation more intuitive, i would suggest to add both the current page number and the overall number of pages between the two buttons.

![select_commit_frame](https://user-images.githubusercontent.com/37844219/40306224-26a1864e-5cfe-11e8-848e-9c946dd97f32.png)

**Comment by ankur-1989** [comment]
@mac24079

 As you are working on the Pagination issue #38, is that possible for you to fix this also?

Both have similar kind of work.

**Comment by mac24079** [comment]
No worries. I'll take this.

Regarding #38 , I opened a branch feat/issue38 but at present, it's not in a state to merge. The pagination functionality is working, just needs a little alignment so that it can look more presentable. WIll fix that soon and look into this.

**Comment by mac24079** [comment]
Merged with https://github.com/ABenchM/abm-frontend/pull/203#event-1963431811
