### ISSUE TITLE
Implement 'Manage Public Collections' page for admin

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#131]
- [x] develop the html && css

- [x] write test cases

- [x] integration with backend

**Comment by nguyenLisa** [comment]
Thanks. Do you have more details on what this WP will entail?

**Comment by TalalE** [comment]
Html and css files could be found in the #180  branch request. 
#180  branch has  changes to the navigation bar and  manage public collections component  with its html and css files.

**Comment by vishaljcj** [comment]
@TalalE please update the status on this issue.

**Comment by vishaljcj** [comment]
done with PR #259
