### ISSUE TITLE
Implement 'Manage Users Page' for admin

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#132]
- [x] develop html && css

- [x] write test cases

- [x] integration with backend

**Comment by nguyenLisa** [comment]
Thanks. Do you have more details on what this WP will entail?

**Comment by vishaljcj** [comment]
curently working on writing test cases with http service calls. rest all functionalities have been implemented.

**Comment by vishaljcj** [comment]
changes have been pushed with #222
