### ISSUE TITLE
Implement 'Pending Requests' page for admin

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#133]
- [x] develop html && css part

- [x] write test cases

- [x] integration with backend

**Comment by nguyenLisa** [comment]
Thanks. Do you have more details on what this WP will entail?

**Comment by vishaljcj** [comment]
@nguyenLisa This work has to be done within 2 months. Sept 30th is the deadline. First 3 weeks would be dedicated to developing the html and css part. Then depending upon how much work has been done on the backend part, we would be doing the integration. This would take another 2 weeks. 3 weeks would be required for writing the test cases. Since there are 4 main UI screens for the first milestone(User Profile && Admin interface implementation), each one of us would be working on one respective screen(also including testing and integration).

**Comment by nguyenLisa** [comment]
Thanks for the information. Could you put those details in the description? #124 ?

**Comment by vishaljcj** [comment]
@nguyenLisa I don't think that #124 is the right issue for this, since it is related to building a collection. cud u please let me know in which all issues you want this description to be added.

**Comment by nguyenLisa** [comment]
No, I meant, inspire yourself of how #124 is described to cut the work of the large WP in smaller ones.

**Comment by vishaljcj** [comment]
@Minal0110 please update the status on this issue.

**Comment by Minal0110** [comment]
Test cases are written and passed, pulled request to develop will be raised thus closing this issue
