### ISSUE TITLE
Create the master page template

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#134]
A proper master page has to be created with the ABM logo, main navigation bar and user icon with required functionalities.

It should look somewhat similar to this....

![screenshot from 2018-08-01 13-53-35](https://user-images.githubusercontent.com/37999970/43520346-dd304202-9592-11e8-916d-e443ace02f9f.png)

**Comment by mac24079** [comment]
I am leaving the topmost part i.e. the image of the user at the moment for the issue #7 . Once it is done here, I will integrate that into #7 .

**Comment by vishaljcj** [comment]
@TalalE please update the progress on this issue, and if completed, comment and close the same.

**Comment by mac24079** [comment]
@TalalE - Any updates?

**Comment by TalalE** [comment]
Changes could be found in #180 branch. 
This issue is completed.
