### ISSUE TITLE
Slides - to keep in the slider-control for application's Landing Page 

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#139]
This is a follow-up fro the issue #67 . 

At present, the front-end team has decided to keep 3-4 slides that will help the user to grasp information quickly about the application and provides easy navigation.

**Comment by mac24079** [comment]
Slides to keep at the landing page slider-control.

1. **Intro about ABM** like what ABM is and whom the application is for?

2. A page about **what a collection is** and **what are the open-supported platforms** the application supports.

3. How to **create a collection**.

4. Do you want to **contribute** to the application? 

Regarding point 4, we are not sure whether to take this or not? 

@nguyenLisa  Kindly provide your suggestions.

**Comment by nguyenLisa** [comment]
Thanks for the suggestions. We should definitely have a "how to contribute" section. But is a slider needed? All of the information could perhaps fit in an "About" page. This would keep things simpler and you could focus on the more important pages.

**Comment by mac24079** [comment]
As per my view it is not required but since, as per the design document it is one of the goals that was discussed, I opened the same as git issue. We can skip this and keep the about page as same it is. Also, all the points above were taken from the existing about page.

**Comment by nguyenLisa** [comment]
After the meeting yesterday with @vishaljcj , @TalalE , @Minal0110 and @mac24079 , I think that getting the UI for the main pages done is a lot more pressing. We have to catch up so that we don't get late at the very start of the project. This is less important, so I would like you to concentrate your efforts in more important parts of the UI. Please confer with @vishaljcj to determine which issues to fix and let me know which issues those are by tomorrow.

**Comment by mac24079** [comment]
**Little late but I get your concern now.** 

**First,** this issue was opened to be done somewhere in October duration and not at present.  **Second,** to make sure things are in hand and we won’t waste much time on discussions when actually implementing it I opened this and labeled under “Questions”. 

**Also,** I discussed with @vishaljcj yesterday to let me know what are the issues/problem that is problematic and needs to be done. He replied that he is presently working and let me know for the same.

**Comment by nguyenLisa** [comment]
We are not doing the slider anymore, but we should think about the landing page instead. I suggest we make it the public collections page. Could you set that up please?

**Comment by mac24079** [comment]
https://github.com/ABenchM/abm-frontend/issues/250#issuecomment-449754216 Hence, closing this one.
