### ISSUE TITLE
Add a search bar to the "Select a commit"-Frame in the "Edit Collection"-Webpage

### ISSUE THREAD

**Issue by johannesduesing** [ABenchM/abm-frontend#14]
When selecting a certain commit for a project, the user has to deal with a long list containing lots of information for all commits available (see screenshot below).
A search bar at the top of that frame would enable the user to search for the characteristics he is interested in rather than having to scan through the whole list.
 
![select_commit_frame](https://user-images.githubusercontent.com/37844219/40306560-6a756c7c-5cff-11e8-98b9-963287133a13.png)

**Comment by ankur-1989** [comment]
Hi Team, 
Any update on this issue?
Thanks!!

**Comment by mac24079** [comment]
Merged with https://github.com/ABenchM/abm-frontend/pull/203#event-1963431811
