### ISSUE TITLE
Update prompt text on Create Collection page

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#142]
Suppose a user navigates to the create collections page for the first time where a prompt text appears(see figure), that's fine for the first time. But the text appears every time, **which can make a user confuse and make them navigate to (My collections)** see whether they have their existing collections or not.

Instead of, either we can remove the text or can make it simple like: **Search projects to create your collection**

![image](https://user-images.githubusercontent.com/23357897/44307396-19579600-a3a2-11e8-89f7-ea1bb972c38d.png)

**Comment by mac24079** [comment]
@nguyenLisa 

text - " To create a collection, search your projects and add them to your collection"

or

text - " To create a new collection, collect projects using the search feature and create a collection from them in the Projects tab or clone an existing collection. "

Thanks.

**Comment by nguyenLisa** [comment]
"Search for projects to add to your collection."

**Comment by mac24079** [comment]
merged with https://github.com/ABenchM/abm-frontend/pull/226#event-2011149971 .

Hence, closing this.
