### ISSUE TITLE
Create the layout for the 'Pending Requests' page

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#157]
Implement the html/css for the pending requests table in this page. The table should have the important information about the users, along with a approve/reject button in each row. Each click on a button should be followed by a pop-up displaying the relevant action performed.

Should look somewhat similar to 
![screenshot from 2018-08-29 21-26-34](https://user-images.githubusercontent.com/37999970/44810742-f6fc1e80-abd2-11e8-8e70-dfd7d2a311c2.png)

**Comment by vishaljcj** [comment]
@Minal0110  please update the progress of this issue, and if it is completed comment and close this issue.

**Comment by Minal0110** [comment]
Layout is created for Pending requests and few modifications are in progress.

**Comment by Minal0110** [comment]
layout is completed, closing this issue

**Comment by Minal0110** [comment]
Layout is completed, closing this issues.
