### ISSUE TITLE
Implement Forget password functionality

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#164]
A button functionality will be implemented to allow the user to reset the password when forgotten. The functionality will be done in collaboration with the implementation of the back-end team. 

https://github.com/ABenchM/abm/tree/anitha_usermanagement_dev

**New**
Changes included in: https://github.com/ABenchM/abm/pull/184

**Comment by mac24079** [comment]
@nguyenLisa 

Since username is a primary key, back-end team has given functionality to recover the password with writing username or email-id. 
For our application, we should keep this or a user should only recover the password with their e-mail? (which is a case in general).

**Comment by nguyenLisa** [comment]
I think there's no harm in allowing the userid as well. The functionality should still be the same though: even if the user enters the userid, an email is sent to the corresponding email.

**Comment by mac24079** [comment]
Rough sketch/prototype for the task.

![prototype_resetpassword](https://user-images.githubusercontent.com/23357897/47614371-452c8180-da9f-11e8-91cc-f1ec5eda18c9.JPG)

**Comment by mac24079** [comment]
Merged with https://github.com/ABenchM/abm-frontend/pull/273.

Hence, closing.
