### ISSUE TITLE
Implement "Delete Project(s)" button in "Edit Collections" page

### ISSUE THREAD

**Issue by ishwaryaPaderborn** [ABenchM/abm-frontend#17]
The user might want to remove projects from his private collection. Therefore, a button that allows him to remove the current selection (that might be an arbitrary number of projects) would be an improvement.

**Comment by nguyenLisa** [comment]
This feature should not be shown at all.

**Comment by nguyenLisa** [comment]
Ah no. I meant that this feature shouldn't be shown if the user doesn't have the right to delete the projects (e.g. the collection is private). Else, it should be shown.

**Comment by ankur-1989** [comment]
Implemented and pushed to develop branch. Closing this issue now. can be reopened if somebody finds any issue.
