### ISSUE TITLE
checking if dockerizing the complete application is feasible or not.

### ISSUE THREAD

**Issue by ankur-1989** [ABenchM/abm-frontend#171]
There are four application components which are connected to each other and need to be dockerized to dockerize the complete application.

- Angular Front end runs at 4200

- NodeJs backend runs at 3000

- Osgi java application runs at  8080

- Mysql application

**Comment by ankur-1989** [comment]
As part of this issue, I could create a docker compose file which will connect these components as a service and these services will be communicating with each other. But we need OSGi java and MySQL application also in the form docker container service to make the application work. I am still searching for the options if docker containers can talk to host services so that we don't need to convert existing services into docker container service.

**Comment by ankur-1989** [comment]
I did not find the feasible option to dockerize the complete application. Therefore, closing this ticket now.

**Comment by nguyenLisa** [comment]
Thanks for looking into that @ankur-1989 . Could you detail why we can't dockerize ABM?
