### ISSUE TITLE
SMTP Exception while sending emails to non-uni email address.

### ISSUE THREAD

**Issue by ankur-1989** [ABenchM/abm-frontend#178]
As of now, when we register the user in ABM and email goes to a non-uni email address, then we get SMTP exception 
"com.sun.mail.smtp.SMTPSendFailedException: 550-5.7.1 Your message was rejected due to spam filtering. Please see
550 5.7.1 http://www.sophos.com/security/ip-lookup?ip=79.225.203.159"

As per SMTP codes, we found the following possible scenarios -

SMTP Code 554. 5.7.1 is a rejection from the Recipient Domain. SMTP Code 554. 5.7.1 means 'Not allowed'. The address in 'Mail From' appears to have insufficient submission rights, or is invalid, or is not authorized with the authentication used; the address in an RCPT TO command is inconsistent with the permissions given to the user; the message data is rejected based on the submitting user. A 5xx level status code indicates a "terminal" status and SMG will not attempt to redeliver the message.

Possible scenarios:

    IP has been included in a Real-Time Blacklist due to Spam coming from your domain.
    Your domain/IP has been blacklisted by the recipient

Steps to reproduce the issue:- 

1. Provide the following details in build.bnd file under CNF folder
  

> emailadminAddress= desired non uni email address
serverHost=mail.uni-paderborn.de
serverPort=25
userAddress=abm-notifications@lists.upb.de
userName=abm-notifications
> userPassword=Unused

2. Start the application 
3. Go to User registration form.
4. Fill in the complete details
5. Submit the Registration form.
6. you will get the SMTP issue in the logs.

**Comment by Chinmay-92** [comment]
**A small note** after having conversation(2 weeks ago) with a network person @uni faculty:

- Server should be connected to University's network in order to use SMTP service via uni email address.

- Hence, If we are trying to connect outside Eduroam i.e. uni network, then IP/domain will be blocked to use uni smtp service to send emails to any non uni email address.

**Comment by nguyenLisa** [comment]
@Chinmay-92 I think @ankur-1989 refers to running the application on the ABM server. The server is on the uni network, yet it cannot send emails outside. Could you look into that?

**Comment by vishaljcj** [comment]
This issue has been resolved now.
