### ISSUE TITLE
'Admin Pending Requests' services integration with frontend

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#183]
Services for approval and rejection of user registration requests has to be integrated with the 'Pending requests' page.

**Comment by vishaljcj** [comment]
@Minal0110 please coordinate with @anut347 and integrate these services into the page.

**Comment by Minal0110** [comment]
approve and reject buttons are integrated with backend #190.
Once @anut347 will update on backend code for multiple selection of user, integration will continue.

**Comment by vishaljcj** [comment]
closing this issue as it can be tracked through #133
