### ISSUE TITLE
Add a column to the "My Collections" table that gives quick access to collection actions

### ISSUE THREAD

**Issue by johannesduesing** [ABenchM/abm-frontend#19]
To improve the user's workflow, an additional column should be added to the "My Collections" table. For private collections, this column should contain a button labeled "Make public", for public collections it should be "Pin".

**Comment by ankur-1989** [comment]
As of now, we are already showing the following columns 

Name , Description , Creation_date , Id , Built Status and Private Status for private collections therefore less space to add more things on the table. Moreover, there are other features also along with "Make public" which are good to have for quick access but less space. 

Regarding Pin button , we are already providing Pin/Unpin button on public collections. 

So, Do we need this feature ?

**Comment by lisa** [comment]
@ankur-1989 I think you mean another Lisa? :)

**Comment by nguyenLisa** [comment]
Let's have the quick accesses accessible with a right-click on the collection.

**Comment by ankur-1989** [comment]
Do you mean context-menu ?

**Comment by ankur-1989** [comment]
Hi Team,

Any update on this issue?

Thanks !!

**Comment by mac24079** [comment]
@ankur-1989 
I have made the changes for the same and used PrimeNG alert message for the same. Since the application is now migrated from 5 to 6, I am facing some issues to include the library as per version6. Will update the same by the end of this weekend.

**Comment by mac24079** [comment]
Closing this one as it is already there.
