### ISSUE TITLE
Integrating back-end API for user profile component.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#196]
Reference issue: https://github.com/ABenchM/abm-frontend/issues/160.

Integrating methods written in back-end:

- [x] getUserList         - to populate the data of user

- [x] postDeleteUser  - to delete user account

- [x] postUsername   - to update user details.

**Comment by vishaljcj** [comment]
@mac24079 please check the postUsername part...please refer [https://github.com/ABenchM/abm/pull/266](url)....

**Comment by mac24079** [comment]
Done and changes will be pushed with one PR. This will be taken care in #7 .

Hence, closing.
