### ISSUE TITLE
Login screen shouldn't be shown if a user has logged in once. Instead it has to be redirected to the default landing page

### ISSUE THREAD

**Issue by ishwaryaPaderborn** [ABenchM/abm-frontend#20]
Once a user login to ABM application and opens in another tab, login screen is shown. But if he clicks on "collections" link in that screen, It takes the user to his/her collections page.

**Comment by ankur-1989** [comment]
This issue has been resolved and pushed to master branch. You can cross check once then I will close this issue.

**Comment by ankur-1989** [comment]
Closing this issue.
