### ISSUE TITLE
Create a user study protocol for the first user study

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#207]
Since we are done with the implementation of first 2 milestones, a user study has to be done for the same.
The protocol has to focus on what can be improved for the functionalities implemented, as well as what can be improved for the next milestone

**Comment by mac24079** [comment]
I have uploaded the created set of protocols at https://git.cs.upb.de/mac24079/pg-abm-user-studies/blob/develop/ABM/UserStudy_Protocols/user_study_1_Mohit.

We all can add our separate files there and then at the end can combile all the versions together.

**Comment by mac24079** [comment]
does anyone updated their set of questions?

**Comment by vishaljcj** [comment]
I will update by today EOD. @TalalE  and @Minal0110 please update yours also

**Comment by mac24079** [comment]
As per @nguyenLisa post on slack: any updates for the same?

I am facing some issues in the repository to push the latest one so uploading the same for reference here. I'll fix them and upload the document there as well.

[user_study_1_mohit_updated.pdf](https://github.com/ABenchM/abm-frontend/files/2637327/user_study_1_mohit_updated.pdf)

**Comment by mac24079** [comment]
The protocol is in the repository now, please add the protocols directly there to keep a track.
https://git.cs.upb.de/mac24079/pg-abm-user-studies/blob/develop/ABM/UserStudy_Protocols/user_study_1_mohit_updated.pdf

Thanks.

**Comment by Minal0110** [comment]
Admin pending request protocol is updated on git, please review and provide your feedback.
https://git.cs.upb.de/mac24079/pg-abm-user-studies/blob/develop/ABM/UserStudy_Protocols/Admin_pending_request_user_study.pdf

**Comment by nguyenLisa** [comment]
Which protocol should I be looking at? Mohit's or Minal's?

**Comment by Minal0110** [comment]
Hello Lisa, I have uploaded updated user study protocol according to cognitive walk-through and waiting for Vishal and Talal to update their user study, once they are done Mohit will combine each user study and provide link of complete user study.

**Comment by nguyenLisa** [comment]
Ok!

**Comment by mac24079** [comment]
@nguyenLisa 
To be more precise, a file(complete protocol) and a link to the repository will be sent to you and @bhermann via e-mail asking for a feedback.

Thanks.

**Comment by Minal0110** [comment]
@nguyenLisa please find below link for complete user study protocol.
https://git.cs.upb.de/mac24079/pg-abm-user-studies/blob/develop/ABM/UserStudy_Protocols/Forntend_User_study.pdf

**Comment by nguyenLisa** [comment]
Thanks. It looks like a good start. Find my feedback below:
- How many participants do you need and what kind of knowledge do they need to have?
- Which introduction and scenarios are you going to run with the participants? Specify the introduction you will give to the users.
- Abstract the tasks to what they need to do. First, identify the main tasks of a user/admin, and ask the participant to perform them. For example, an admin wouldn't filter for the sake of filtering. What is their original intention for which they need the filtering functionality? This is what you should ask of the participant, instead of just filtering.
- What are you going to record? Do you have a consent form for participants to sign it?
- The questions you have make sense, but you should engage the discussion to go further and understand "why". Why does the user behave in a certain way, why do they use certain features or not, etc. Just knowing whether they can do the task or not is fine, but knowing why is the true purpose of this study here.
- Please harmonize the study. This looks like three different studies. Not only are they structured differently, they also have different protocols and the switches would unsettle a participant.
Please let me know when you have a new version to review.

**Comment by Minal0110** [comment]
@nguyenLisa Thank you for the feedback, we are updating user study protocol with introduction, consent form and also updating user study question structure.

**Comment by mac24079** [comment]
@nguyenLisa 
Regarding the consent form, can you provide feedback for the same as if we are missing some stuff or there is some part that is not needed?

![consent-form](https://user-images.githubusercontent.com/23357897/50280170-181ba000-044c-11e9-8c11-38a94ade7476.jpg)

Thanks.

**Comment by nguyenLisa** [comment]
Hi @mac24079 , here is my feedback:
- Why is this consent form paraphrased? Please write an appropriate one.
- Are you expecting Ben and I to handle the user studies? As far as I am concerned, this is your job...
- Missing data about the rights of the user w.r.t. their data: access to it and request to be deleted.
- In the last sentence, the participant should also attest that they are at least 18 years old.

**Comment by vishaljcj** [comment]
@nguyenLisa 

- The consent form was paraphrased just to take an idea of what needs to be there in the form as the team discussed and was not aware of actual content. A proper form will be sent for the same.

- Obviously not. There is another column stating Conducted by - names of the people will be there who will conduct the user study. I looked into the internet and saw some templates, and think this column "study evaluators" is not needed now.

- Sure, I"ll add this.

- I"ll include this as well.

Thanks.

**Comment by Minal0110** [comment]
@nguyenLisa 
while working on user study i came across general doubt. Do we need to conduct user study on implemented UI or conduct user study for collection workflow prototype?

**Comment by Minal0110** [comment]
Hello @nguyenLisa 

Please find below links for user study and consent form
1. Consent form: https://git.cs.upb.de/mac24079/pg-abm-user-studies/blob/develop/ABM/UserStudy_Protocols/Consent_form_for_ABM_User_study.pdf
2. User study: https://git.cs.upb.de/mac24079/pg-abm-user-studies/blob/develop/ABM/UserStudy_Protocols/User_study_version_2.pdf

**Comment by Minal0110** [comment]
Hello @nguyenLisa 

Added metrics and participant information to user study. No user study questions are changed in current version

https://git.cs.upb.de/mac24079/pg-abm-user-studies/blob/develop/ABM/UserStudy_Protocols/User_study_version_2.1.pdf

**Comment by Minal0110** [comment]
Hi @nguyenLisa 

Please find below links for updated user study and consent form

1. Consent form: https://git.cs.upb.de/mac24079/pg-abm-user-studies/blob/develop/ABM/UserStudy_Protocols/Consent_form_for_ABM_User_study_V2.pdf

2. User study: https://git.cs.upb.de/mac24079/pg-abm-user-studies/blob/develop/ABM/UserStudy_Protocols/User_study_version_3_.pdf

**Comment by vishaljcj** [comment]
Since the protocol has been approved, closing this issue.

**Comment by vishaljcj** [comment]
As per the discussions today, user study has to be conducted also on a prototype for Milestone 3 &4( Delphi Integration & Collection Management). This requires a new prototype to be implemented as well as the updating of of the user study protocol. Hence reopening this issue.

One version of the prototype is attached below. This has to be modified as per the new requirements.
[prototype.zip](https://github.com/ABenchM/abm-frontend/files/2817451/prototype.zip)

**Comment by anitha181992** [comment]
[Balsamiq_Prototype.zip](https://github.com/ABenchM/abm-frontend/files/2840342/Balsamiq_Prototype.zip)

**Comment by anitha181992** [comment]
Updated prototype:
[Balsamiq_Prototype.zip](https://github.com/ABenchM/abm-frontend/files/2840488/Balsamiq_Prototype.zip)

**Comment by mac24079** [comment]
@anitha181992 

The demonstration you gave me of the above prototype is somehow I mixed, can you please write the steps like what is the workflow you have created in this?

Thanks.

**Comment by Minal0110** [comment]
Hi @nguyenLisa 

Please find below link for collection workflow user study questions.
https://git.cs.upb.de/mac24079/pg-abm-user-studies/blob/develop/ABM/UserStudy_Protocols/Collection_WF_User_study.pdf

**Comment by nguyenLisa** [comment]
Do you need me to do anything with that?

**Comment by Minal0110** [comment]
Hi @nguyenLisa, @anitha181992 and @mac24079  
Uploaded user study for everyone's reference.

**Comment by Minal0110** [comment]
Hi @nguyenLisa 

The User study result document is uploaded on git, below is the link for the same. I would like to request you to review the document and provide your feedback.
https://git.cs.upb.de/mac24079/pg-abm-user-studies/blob/develop/ABM/Performed_User-study/Update-ABM-UserStudy.pdf

**Comment by nguyenLisa** [comment]
This looks good @Minal0110 , thanks! Please discuss the feedback with the group, and add it into the issue tracker, for future work (by the PG or others).

**Comment by Minal0110** [comment]
@nguyenLisa thanks for quick review, we have already created some issues and we will add some more.

**Comment by Minal0110** [comment]
Closing this issue as user study is completed and user study result document is available on Git.
