### ISSUE TITLE
Make all existing tables cosistent with that of Admin tables

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#209]
Currently the tables for MyCollections, Public Collections and Search Projects are using bootstrap. Change them to use angular material so that they are consistent with the tables that have been created for Admin functionalities.

**Comment by mac24079** [comment]
@vishaljcj @TalalE 
Please leave the **Search projects** part of the table as I am taking care of that in #206 so better we not mix it up. Thanks.

**Comment by mac24079** [comment]
@Minal0110 
As you are working on this, I would like to move your attention to the above comment. I have changed the table appearance from primeNg to Angular material format that appears on the Create collection page when we search for the projects so please exclude that from your list to avoid redundancy of work and code.

Thanks.

**Comment by Minal0110** [comment]
@mac24079, currently i am working on public collection, if i have any query regarding create collection search for project tab, i will get back to you.

**Comment by vishaljcj** [comment]
This issue will be handled in Milestone 4 through #244 and #248 . Hence closing this for now
