### ISSUE TITLE
Allow the user to modify name and description of a project

### ISSUE THREAD

**Issue by johannesduesing** [ABenchM/abm-frontend#21]
For a better understanding of each project inside a given collection, the user might want to assign individual names and descriptions to single projects. Therefore, after adding a project to his collection, the user should be asked whether he wants to edit the existing name and description of the project, followed by a dialog that allows him to enter individual names and descriptions.

**Comment by ankur-1989** [comment]
Hi Team,

Any update on this issue?

Thanks!!

**Comment by mac24079** [comment]
@ankur-1989 

I am looking into this and will raise a PR soon.

Thanks.

**Comment by mac24079** [comment]
As discussed with @vishaljcj : Could you please confirm that this is no longer needed.

Referenced Comment: https://github.com/ABenchM/abm-frontend/issues/272#issue-404914644 

Thanks.

**Comment by vishaljcj** [comment]
yeah..this is no longer needed as we will be persisting only the maven id in the DB.

**Comment by mac24079** [comment]
Okay, hence closing this one.
