### ISSUE TITLE
Include the newly implemented relevant fields in the Registration page

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#210]
Fields such as 'Firstname', 'Lastname' that have been added to the User DAO, should be integrated into this page.

**Comment by Minal0110** [comment]
Added Lastname field to registration page

**Comment by Minal0110** [comment]
closing this issue

**Comment by mac24079** [comment]
![image](https://user-images.githubusercontent.com/23357897/48904955-77dc5680-ee60-11e8-94e3-6e0efcb905fd.png)

**Comment by mac24079** [comment]
merged in frontendpg
