### ISSUE TITLE
Add asterisk(*) to the mandatory fields on registration page.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#213]
At present, when a user navigates to the registration page there are fields which are mandatory, but an asterisk should be added to give a clear view to the user that the required fields are necessary to be filled and can not be blank.

**Comment by mac24079** [comment]
@nguyenLisa 

Would this be fine (below figure) for this issue? 
![image](https://user-images.githubusercontent.com/23357897/49942864-c53f6700-fee6-11e8-9105-cdffd0e0b2a3.png)
**OR**
Shall we make the consistency of asterisks? like the aesterisk at the end should be alligned in the same order like a below sample.
![image](https://user-images.githubusercontent.com/23357897/49943041-2d8e4880-fee7-11e8-9773-edbc879fd6c4.png)

**Comment by nguyenLisa** [comment]
The figure with the * afterwards looks good. Thanks!

**Comment by mac24079** [comment]
Hey @ankur-1989 
Actually, I fixed the linting errors in this but don't know why they were appearing again and so for the same I mentioned the commit message in addition to the Fix issue, but I am attaching now the figure for the same regarding the passing of all files passing the linting error for the new PR.

![image](https://user-images.githubusercontent.com/23357897/50059289-4582f800-0185-11e9-9fce-d7b2f33fa8b4.png)


Thanks.

**Comment by mac24079** [comment]
Merged with https://github.com/ABenchM/abm-frontend/pull/241. Hence, closing
