### ISSUE TITLE
Fix Responsive Layout

### ISSUE THREAD

**Issue by johannesduesing** [ABenchM/abm-frontend#22]
When reducing the window size the layout is displayed incorrectly as seen in the following picture where the page header cuts of half of the text. 
![responsive_layout_broken](https://user-images.githubusercontent.com/37844219/40311578-80bea29e-5d10-11e8-9130-f6ee07ad690e.png)
This might be related to the changes introduced in https://github.com/ABenchM/abm/issues/8

**Comment by anut347** [comment]
Closing this issue since the issue does not seem to appear in the new ABM.
