### ISSUE TITLE
Navigation color tab for the user is different.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#228]
At present we have different color for the user_name tab(picture).
![image](https://user-images.githubusercontent.com/23357897/49343953-383c1880-f671-11e8-90ae-c948fe9c8305.png)

**Comment by mac24079** [comment]
@nguyenLisa 

Hello, I just noticed that the navigation tab color for the user(name) is different than the other tab color's. Is that needs to be the same as it is at the moment(in the picture) or all the navigation-bar tabs should have a consistent one color?

Thanks.

**Comment by nguyenLisa** [comment]
This is a bug. Good catch, thanks! The colors should be the same. Could you fix this?

**Comment by mac24079** [comment]
Merged with: https://github.com/ABenchM/abm-frontend/pull/236.

Hence, closing.
