### ISSUE TITLE
Move action column of "Selected Projects" table to the left

### ISSUE THREAD

**Issue by johannesduesing** [ABenchM/abm-frontend#23]
Right now the action column of the "Selected Projects" on the "Create Collection" page is the rightmost column. It's visible only if the description is rather short. If the description of the project gets too long, a scrollbar is displayed, which moves the action column out of sight for the user. This can be seen on both screenshots below.
![selected_collections_overflow_1](https://user-images.githubusercontent.com/37844219/40312143-45e55e86-5d12-11e8-81eb-df8bbb45c8fa.png)
![selected_projects_overflow_2](https://user-images.githubusercontent.com/37844219/40312146-48ecf80a-5d12-11e8-80bb-3b421d9ec057.png)
This could be avoided by moving the action column to the left. Another way to handle this would be to implement a fixed maximal width for the description column, as it is done in the search result table on the same page.

**Comment by ankur-1989** [comment]
Now this is fixed in the new front end and wrapping up the description. pushed the changes to develop branch. closing this issue now.
