### ISSUE TITLE
Create prototypes for milestone 4

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#233]
Based upon what has been discussed in today's meeting create prototypes for milestone 4( collection management) for next week. Do 2 hours of prototyping for this week.

**Comment by mac24079** [comment]
@vishaljcj 

I am still struggling to have a clear view. Can you break this task into subtasks? so that we can avoid a merry chase situation in the future.

Thanks.

**Comment by Minal0110** [comment]
Yesterday's MOM
1. Discussed about work flow of create collection, my collection, public collection and Search project(optional)
2. Add version number and version status(Private and public) column to my collection.
3.My collection is divided into my private collection and my public collection.
4.Once a collection is marked public, user cannot edit or delete public collection/version present in my collection.
5. One can derive version from any collection and any version in my collection page.
6. A  user can search different collection available in public collection table.
7. A user can pin preferred collection from public collection table for future use, 
8. User can derive new version from existing collection/ version which will appear as private unless you mark as public.
9. View of deriving version in public collection and my collection will be different, for example edit and delete collection.
10. On create collection work flow @vishaljcj  is working and he can provide us some details.
Please feel free to add any missing point.
Please be ready with prototype by 19th December.
