### ISSUE TITLE
frontendpg branch's ng build run failed  

### ISSUE THREAD

**Issue by Minal0110** [ABenchM/abm-frontend#238]
@mac24079 could you please suggest on app.module.ts changes done by you in frontendpg, due to this changes unable to run build. 
![app module ts error](https://user-images.githubusercontent.com/37415168/50023957-1fbcee00-ffe1-11e8-81e4-4ebb9fb3bd34.png)

**Comment by mac24079** [comment]
@Minal0110 
The develop branch contains a lot of things that were no where in the frontendpg branch as we are just working on the PG milestones and issues etc. but the develop branch is ahead of that.

Also, It seems after pulling the changes from the front-end branch you didn't run the npm install command to install the packages that were already there in the develop branch. You must follow the basic commands to run and test it:
1. pull the changes.
2. run the npm install command
3. go the directory of the main folder of the sr-project - and run npm install again.

Probably, the error will go away. Please let me know in case you need any further assistance.

Thanks.

**Comment by Minal0110** [comment]
@mac24079 thank you for the suggestion and clarification, closing this issue.

**Comment by Minal0110** [comment]
@mac24079 thank you for suggestion and clarification, closing this issue.
