### ISSUE TITLE
Invalid default values for name and description of a new collection

### ISSUE THREAD

**Issue by johannesduesing** [ABenchM/abm-frontend#24]
If a user creates a new collection and did at some point in the past already create another collection, the name and description of the old collection will be the default values for the new collection's name and description. This should not be the case, as it will easily lead to multiple collections with the same name and/or the same description. Instead, we should settle for more generic default values like "name" and "description".

**Comment by ankur-1989** [comment]
Fixed in new front end and pushed to develop branch. Closing this issue.
