### ISSUE TITLE
Only a version of a collection can be made as public.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#243]
At present, after creating a collection a user is able to make the entire collection as public instead, a user should only be allowed to make a version of a collection as public.

**Comment by ankur-1989** [comment]
@mac24079 
Which branch are you checking ? 
User can not make a collection public and we make collection public version wise only.  This functionality is already there in Master and develop branch.

**Comment by mac24079** [comment]
Hello @ankur-1989 ,

I checked the develop branch. I am following the below steps(please correct me if I am wrong).

A.
1. I created a new collection - "makepublic".
Now, when I created a new collection, that collection appears directly on the My collections Page.
2. When I right click that collection, it asks me to make that collection as public and when you click the status changes to Public.

B.
1. I created a new collection - "makepublic".
Now, when I created a new collection, that collection appears directly on the My collections Page.
2. I opened the collection and derived new versions for that collection.
Still, if I come back to the My collections page, I am able to make the collection as public.

![image](https://user-images.githubusercontent.com/23357897/50334548-f3393280-0508-11e9-8e28-106a2cb580aa.png)

**Comment by ankur-1989** [comment]
Hi,

I did not get the second part. If you open the collection and click on make public button then it makes the current version public and still, the collection is private. Are you able to follow this?

we need to take care of context-menu one.

Best Regards,
Ankur Gupta

**Comment by mac24079** [comment]
For the second part, I mean to say, if I create a collection and suppose I derive four versions from that collection and then just come to My collections tab and then make that collection as public, the context menu service makes the collection as Public i.e. the status changes to Public that time. So, If I need to know which version is public it is not able to know as the whole collection becomes public.

Thanks.

**Comment by ankur-1989** [comment]
Yes, it is because context menu is making the whole collection public and it had not changed. but if you use the internal one then it works as per the expectation. So we should rephrase the title of the issue to make it specific.

Best Regards,
Ankur

**Comment by mac24079** [comment]
This is taken care in the PR: https://github.com/ABenchM/abm-frontend/pull/279

Hence, closing.
