### ISSUE TITLE
Integrate filters into the Search page

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#248]
- Solve the CORS issue mentioned in #237 

- The search box should now take DSL query as input instead of Search keyword.

- Get the list of all filters from delphi and display it in a table with pagination, sorting and filtering options.
Add a field 'Value' where the user can type a value corresponding to a selected filter. This should look somewhat like
![image](https://user-images.githubusercontent.com/37999970/50301648-369f8c80-0488-11e9-89be-fed6cd5d97e1.png)

- Clicking on 'Search' should call the corresponding Delphi API with the DSL query. The results returned should be parsed and displayed in a table.

- Selecting a specific project from the above mentioned table should populate it into 'Selected projects' table which would be maintained even if the user wishes to perform another query.

![image](https://user-images.githubusercontent.com/37999970/50301980-00aed800-0489-11e9-8a96-d679b0d9d201.png)

**Comment by vishaljcj** [comment]
Below is the prototype
[prototype.zip](https://github.com/ABenchM/abm-frontend/files/2791839/prototype.zip)

**Comment by Chinmay-92** [comment]
@iamebuka Here is the description 
* Clicking on 'Search' should call the corresponding Delphi API with the DSL query. The results returned should be parsed and displayed in a table.
* Selecting a specific project from the above mentioned table should populate it into 'Selected projects' table which would be maintained even if the user wishes to perform another query.

**Comment by iamebuka** [comment]
pull request on issued has been accepted and merged
