### ISSUE TITLE
My Collection's table is not displaying proper data of Collections of a user.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#251]
At present, there are 30 total collections for the user, 

![image](https://user-images.githubusercontent.com/23357897/50417697-0c532380-0828-11e9-9b1c-f1150466776e.png)

but only 7 are appearing in the My collections table.

![image](https://user-images.githubusercontent.com/23357897/50417711-1b39d600-0828-11e9-84b3-9ef422baa7b6.png)

**Comment by nguyenLisa** [comment]
Hi @mac24079 , in which branch(es) does this error occur?

**Comment by mac24079** [comment]
@nguyenLisa 

This issue is in the develop branch. Though I thought this could be an issue with the system locally I observed the same issue in the laptop of @vishaljcj (last Sunday).

Thanks.

**Comment by ankur-1989** [comment]
@mac24079 
Are you looking into this issue as well ?
BR,
Ankur

**Comment by mac24079** [comment]
@ankur-1989 

Yes, the problem is with the paginator. As there was a discussion in the Project Group and we are moving the tables structure from primeNg to AngularMaterial. I will address this issue with the same and will raise a PR. I hope that would be fine.

Thanks.

**Comment by mac24079** [comment]
This issue is getting addressed in #260 . Hence, closing,
