### ISSUE TITLE
Remove button is not working on Create Collection Page

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#252]
At present, when a user creates a collection and adds projects to a new collection/existing collection. A small table at the top appears that displays the number of selected projects that a user selects. Till here everything is fine, but when the user tries to remove a project from the selected projects by clicking the Remove button, an error appears (figure).

![image](https://user-images.githubusercontent.com/23357897/50424928-7215ce80-086d-11e9-8a46-e82d31f9baa5.png)

**Comment by nguyenLisa** [comment]
Hi @mac24079 , in which branch(es) does this error occur?

**Comment by mac24079** [comment]
@nguyenLisa 

This issue is in the develop branch. I fixed it and will raise a PR for the same.

Thanks.

**Comment by vishaljcj** [comment]
Closing this as it has been merged to develop
