### ISSUE TITLE
Forgot Password button is not working - Develop branch.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#254]
At present, there is a Forgot Password link which is displaying on the Login page of the application which is not working. The link was pushed in #242 (src/app/login/login.component.html). The core functionality for the Forget password will be pushed later after some other PR's of the frontendpg branch, so the link to the Forgot Password button can be removed at the moment from the develop branch as it is not working.

![image](https://user-images.githubusercontent.com/23357897/50545470-e9a08080-0c14-11e9-843c-f6be0c736866.png)

**Comment by mac24079** [comment]
@nguyenLisa 

What did you suggest?

Thanks.

**Comment by nguyenLisa** [comment]
Let's just remove this functionality for now. We'll put that back later. Thanks for catching that.

**Comment by mac24079** [comment]
The fix is in develop branch. Hence, closing.
