### ISSUE TITLE
Change 'My Collections' table View 

### ISSUE THREAD

**Issue by TalalE** [ABenchM/abm-frontend#260]
1.The Grid should be changed from primeng to angular material.
2. Versions inside the collection should be presented.
3. The status of each version should be presented.
4. Add button to make the version public if it is private.

**Comment by mac24079** [comment]
@TalalE 

Please consider the point addressed in #251 as @vishaljcj confirmed that you will be raising the PR for the change of My Collections table from primeNg to Angular material.

**Comment by mac24079** [comment]
Merged in https://github.com/ABenchM/abm-frontend/pull/279. 

Hence, closing this.
