### ISSUE TITLE
Manage Public Collections tab is not working.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#265]
When a user clicks the Manage Public Collections tab following error is coming:

![image](https://user-images.githubusercontent.com/23357897/51962803-64b0bd00-2487-11e9-95df-e06fa8a279c6.png)

Branches tested:
Front-end : develop branch
Back -end : develop branch

**Comment by vishaljcj** [comment]
The code for this has not been pushed yet and will be done with PR #259. The routing has not been provided for this tab, and thats y this error pops up. So if there are no other issues, could you please close this issue.

**Comment by mac24079** [comment]
@vishaljcj 

Sure, no other issues other than the stated one. I think since it is not working in the develop branch at the moment, I think this can remain open as some other might notice the same error and opens it again.

**Comment by vishaljcj** [comment]
working fine now
