### ISSUE TITLE
Alert on Pending request page.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#266]
@nguyenLisa 

At present, on the **Pending request pag**e, an admin can approve/reject the user by just single clicking on the icon, but in case of mistaken action done, admin won't be able to redo the action taken. So, in that case **should we have an alert** like we have when deleting a user on the **Manage users tab**?

![image](https://user-images.githubusercontent.com/23357897/51966191-d0982300-2491-11e9-9a63-5b9528ed2f63.png)

Thanks.

**Comment by nguyenLisa** [comment]
No that's fine. Accepting/rejecting users is not critical, as users can re-apply later. Having this window would be a hindrance if an admin would like to accept/reject multiple people in a row.

**Comment by mac24079** [comment]
sounds cool.

Hence, closing.
