### ISSUE TITLE
Collection name displayed even after deleting the collection in 'Select a Collection' list in 'addtocollection' page

### ISSUE THREAD

**Issue by 24santoshr** [ABenchM/abm-frontend#27]
The Collection name is displayed in 'add to collection' page under 'Select a Collection' list even though it has been deleted.

Steps to reproduce:-

i) Create a new Collection.
ii) Delete that Collection.
iii) Search for a project repository in 'search' page. Select any project.
iv) Click on 'Add this project to a collection'/'Add all selected projects to a collection' button.
v) The deleted collection is still displayed in the 'Select a collection' list.

![java_1](https://user-images.githubusercontent.com/32432999/40315467-c5e6d408-5d1b-11e8-8ed3-b682cc4a1b18.png)
![java_2](https://user-images.githubusercontent.com/32432999/40315468-c60eb89c-5d1b-11e8-8f5d-aa4f413c227e.png)
![java_3](https://user-images.githubusercontent.com/32432999/40315469-c6445e16-5d1b-11e8-934a-51b46dfb6d09.png)
![java_4](https://user-images.githubusercontent.com/32432999/40315470-c6651d86-5d1b-11e8-8488-7070e12157e3.png)

First screenshot displays a new Collection created called 'Java Project'. Second screenshot shows the deletion of that Collection. Third screenshot shows the updated homepage where the collection 'Java Project' has been deleted. Fourth screenshot shows the Collection name still appearing in 'Select a Collection' list after deletion.

**Comment by ankur-1989** [comment]
Fixed this issue in new front end and pushed the changes to develop branch. Therefore, closing this issue.
