### ISSUE TITLE
Derivation of new version should now include a version name

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#271]
As a new attribute Version name is being added to the version table, the following changes have to be accounted for

- While deriving a new version, an input box should be displayed where the user can provide a name for the newer version he/she wishes to create. This field should be mandatory.

- While creating a new collection, user should be given the option for entering a version name which would be used for version 1 created by default.

**Comment by mac24079** [comment]
Merged with https://github.com/ABenchM/abm-frontend/pull/290.

Hence, closing.
