### ISSUE TITLE
Modify the view for 'Projects' table for a version

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#272]
As currently Delphi crawls only from Maven repositories, there wont be any commits/tags/branches. This has to be removed from the current implementation. The  only information what would be displayed instead would be the id/maven repository url of the projects and options to add/remove projects.

**Comment by mac24079** [comment]
unassigned as per discussion with @anitha181992 .

**Comment by mac24079** [comment]
Merged with https://github.com/ABenchM/abm-frontend/pull/304.

Hence, closing.
