### ISSUE TITLE
Enhance Create Collection View

### ISSUE THREAD

**Issue by TalalE** [ABenchM/abm-frontend#281]
1. Use Angular material component for search field and buttons. 
2. Put small space between the buttons below selected project table and space between the table and buttons.
3. Make search field full width and decrease the spaces between it the tables above and below.

**Comment by mac24079** [comment]
Unassigned @TalalE after discussion with @TalalE and @vishaljcj .

**Comment by mac24079** [comment]
Merged with https://github.com/ABenchM/abm-frontend/pull/308.

Hence, closing.
