### ISSUE TITLE
Admin user should not be listed in Manage user tab 

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#285]
At present, I am the one user who is an admin. Question comes:
 
1. Should the admin user be shown to manage its account in the Managae users tab?
2. Also what is the use of keeping the Action status as active, because if the admin locks istelf and then tries to login or delete the user itself then it won't be able to login again.

Because of point2, I think the admin should not be appear in the Manage users tab.

![image](https://user-images.githubusercontent.com/23357897/53177704-ca104d80-35f0-11e9-9d3b-4bff96af5504.png)

@vishaljcj - Please let me know.

Thanks.

**Comment by vishaljcj** [comment]
Yeah, please correct that.

Thanks.

**Comment by mac24079** [comment]
@anut347 @Chinmay-92  @anitha181992 - this can be taken care in the backend itself. @Minal0110 is opening the same in the ABM repository, please coordinate the issue once with the front-end as well and when working fine please write here if anything needs to be taken care at the front-end.

Thanks.

**Comment by anut347** [comment]
Hi @mac24079 , @vishaljcj , @Minal0110 ,
I've made the necessary backend changes and created PR https://github.com/ABenchM/abm/pull/332.

You'll have to make frontend changes as given below. You'll have to pass two parameters now. 
-for getting user list for pending approval page,  pass 'approved' as 0 and 'username' as the current username
-for getting user list for manage users page,  pass 'approved' as 1 and 'username' as the current username

You can use the branch https://github.com/ABenchM/abm/tree/anu_get_milestone4 to test the frontend backend integration until the PR is merged,

**Comment by mac24079** [comment]
Merged in https://github.com/ABenchM/abm-frontend/pull/287.

Hence, closing.
