### ISSUE TITLE
Admin users should not appear in the Manage Users tab.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#288]
This issue is opened on reference to issue #285 .

The ABM team conducted a user study and found a user confused when every user was listed in the Manage Users tab. The user got confused and deleted one user and the user was Admin with which it was logged in. For the same, the ABM team decided to not list the current user who is an admin in the Manage users tab. For the same PR's have been raised:
https://github.com/ABenchM/abm/pull/332 (back-end).
https://github.com/ABenchM/abm-frontend/pull/287 (front-end).

As per integrating the two PR's now we have the functionality that - If the current user is an Admin then it will not appear in the Manage Users tab but the other user's who are Admin they will be listed in the Manage Users tab (figure below):
![image](https://user-images.githubusercontent.com/23357897/53345795-03f59280-3916-11e9-84f7-b30c82c4cf63.png)

**Question :** Shouldn't every Admin user not be dispalyed in the Manage user's tab ? and only the users who are not Admins should be displayed?

**Comment by mac24079** [comment]
@nguyenLisa 

Could you please provide some insights on this?

Thanks.

**Comment by nguyenLisa** [comment]
An admin should not be able to edit their own profile. If they want to downgrade/delete themselves, they have to nominate another admin who will do that for them.

**Comment by mac24079** [comment]
Sounds good. This functionality is there in develop branch.

Hence, closing this one.
