### ISSUE TITLE
additional space in query after selecting any filter

### ISSUE THREAD

**Issue by Chinmay-92** [ABenchM/abm-frontend#292]
**Describe the bug**
There is an additional space coming in every generated query once we choose a filter with some value.
for example when I selected first filter I got below query:
[if_icmpgt (opcode:163)] >10

**To Reproduce**
1. Go to Create collection page
2. Click on show filtering options
3. Enter value in format >10
4. Click on Apply
5. Check value generated in search box

**Expected behavior**
Space should not be there as it gives HTTP 500 response(query format is not correct)

**Comment by ankur-1989** [comment]
@Chinmay-92 
Have you pulled the latest develop branch? As I am using the latest one and I am not getting any space between the queries.

**Comment by iamebuka** [comment]
@ankur-1989 yes, but when a user enters "> 1" (notice the space between ">" and "1") in the filter value it would throw an error on the server. since that wasn't handled in my last push, so i handled it this time

**Comment by iamebuka** [comment]
PR for this issue has been accepted
