### ISSUE TITLE
Redesign search form of the search component 

### ISSUE THREAD

**Issue by iamebuka** [ABenchM/abm-frontend#316]
Redesign the search form to use chips and collapse the filter table to be a part of the search form, like in the prototype below
![proto_w](https://user-images.githubusercontent.com/11005120/53902511-9813d800-4041-11e9-875d-b5ec558548af.jpg)

**Comment by mac24079** [comment]
@iamebuka 
A slight suggestion:
At present, there is no tooltip nor any placeholder text that can guide a user that they need to make use of "Show Filtering options" button first and only after using that a user can search for projects. So, it would be useful to have a placeholder text or a tooltip on the page.

Thanks.

**Comment by iamebuka** [comment]
@mac24079 nice suggestion, ill sure add it

**Comment by iamebuka** [comment]
issue has been resolved and merged
