### ISSUE TITLE
Add in the "Create Collection" page

### ISSUE THREAD

**Issue by nguyenLisa** [ABenchM/abm-frontend#32]
- [x] Lay out a stub with the typescript, html, css, test files.
- [x] Add in the html components to look like the old interface (see below).
- [x] Link the html components to the backend.
- [x] Re-establish all functionalities.
- [x] When a user clicks on ABM logo he/she should be redirected to ABM homepage.
- [x] Replace the tab icon with ABM logo.

<img width="925" alt="capture d ecran 2018-05-23 a 19 29 07" src="https://user-images.githubusercontent.com/1546847/40440919-b1aa4aa6-5ebf-11e8-8ad8-27d7a3d17607.png">

**Comment by ankur-1989** [comment]
"When a user clicks on ABM logo he/she should be redirected to ABM homepage". part is done.

**Comment by ankur-1989** [comment]
This functionality is already implemented. Therefore, closing this issue.
