### ISSUE TITLE
If username exists it should not allow to register the user with same username.

### ISSUE THREAD

**Issue by ankur-1989** [ABenchM/abm-frontend#33]

**Comment by Chinmay-92** [comment]
@ankur-1989  and @bhermann , @nguyenLisa 
We looked into this issue and it doesn't seems to belong to new ABM-FrontEnd since there is only frontend code and we will have to make changes in backend in order to solve this issue.
Please provide your suggestions.

**Comment by nguyenLisa** [comment]
Then, do the necessary changes in the backend and make sure that the error is reported well in the frontend.

**Comment by ankur-1989** [comment]
Nope, it is a front end change because back-end changes are already implemented. As a hint, you need to focus on /rest/username Rest service in the front end to cater this issue.

**Comment by ankur-1989** [comment]
Shall I close this issue now ?

**Comment by nguyenLisa** [comment]
@Chinmay-92 , @ishwaryaPaderborn , @vishaljcj , did you implement the necessary changes in the frontend?

**Comment by Chinmay-92** [comment]
yes, we have implemented necessary changes in frontend. We can close this issue
