### ISSUE TITLE
Query regarding the new view of the Create Collection page.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#338]
@iamebuka @ankur-1989 

I am unable to use the newly implemented view for creating a collection. Can you please elaborate the steps so that I can use it well. Steps I followed for creating a collection:

1. Selected one of the listed filters.
2. Gave the value.
3. Clicked the Search button.

After that an error appears:
![image](https://user-images.githubusercontent.com/23357897/55416722-a33e2300-556f-11e9-915f-c23f255dbee3.png)

Can you please confirm me what I am missing ?

Thanks.

**Comment by mac24079** [comment]
Also, there is a spelling mistake in the sentence:
Text: An error occured during search (reference-above figure)

Here, the **occurred** spelling is not correct and a full stop is missing at the end.
Suggested text: An error occurred during the search.

Also, a display of something(**text** that please check the filters or values)  stating what could be an error would be useful for the user.

**Comment by ankur-1989** [comment]
@mac24079 
Is your query resolved?
I have fixed the spelling mistake and other suggestions.
Regarding elaborating the error details, I'll see How much errors we can handle.

**Comment by mac24079** [comment]
@ankur-1989 
The query resolved after realizing that some filters need some specific type of value. But yeah if the user already knows about the filters and what type of value they need, then the issue is no more needed.

**Comment by ankur-1989** [comment]
Closing the issue as this issue is no more needed. This was opened for clarification of a feature.
