### ISSUE TITLE
Toggle navigation missing for small device display (320*480)

### ISSUE THREAD

**Issue by Minal0110** [ABenchM/abm-frontend#34]
In the small device the webpage should look more presentable with toggle navigation which is currently missing in ABM 2.0. For reference please find below screen shot of ABM 2.0 which require toggle navigation and please check 2nd screen shot of GitLab which shows more presentable and user friendly  view of webpage.  

ABM 2.0 small device display
![screen shot 2018-05-24 at 12 33 03](https://user-images.githubusercontent.com/37415168/40481214-ff5ba2f4-5f50-11e8-9e03-4b5f51285bea.png)

GitLab small device display
![screen shot 2018-05-24 at 12 41 27](https://user-images.githubusercontent.com/37415168/40481222-06799d66-5f51-11e8-84e6-df5c164b155b.png)

**Comment by vishaljcj** [comment]
This is working in develop as of now. Hence closing this issue
