### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#340]
While logging the application, the username entry is not working correctly. 

For example I have a user name as John (Caps J) and some password, but when logging the application with user name as john and the same password as John, the application allows the user to login into the application with an error message as :

![image](https://user-images.githubusercontent.com/23357897/55888118-1d455c00-5baf-11e9-8c0e-884ae280b469.png)

**Comment by ankur-1989** [comment]
@mac24079 

what error message are you getting?

**Comment by mac24079** [comment]
In front-end:
![image](https://user-images.githubusercontent.com/23357897/55961523-58a75f80-5c6f-11e9-8b68-552d93c3af6c.png)

In back-end:
![image](https://user-images.githubusercontent.com/23357897/55961553-6826a880-5c6f-11e9-9519-1616d204b374.png)

**Comment by ankur-1989** [comment]
Issue has been resolved. Changes are in development branch now. Therefore, closing the issue.
