### ISSUE TITLE
Animated tutorial for user onboarding

### ISSUE THREAD

**Issue by iamebuka** [ABenchM/abm-frontend#343]
**Is your feature request related to a problem? Please describe.**
As a new user of the website, it's difficult to tell what each menu option mean and what actions could be performed.

**Describe the solution you'd like**
For every new user login, I expect the user is presented with some form of an animated tutorial explaining the various sections of the application and what actions can be done, they could play through the tutorial or they could choose to cancel. Cancelling means they would be presented with the tutorial the next time they log in while playing through the tutorial to the last step means they wouldn't be shown the tutorial again.

**Describe alternatives you've considered**
None

**Comment by ankur-1989** [comment]
@iamebuka 
You have forgotten to add "ngx-cookie-service" package in package.json file. I am not able to build the application as it gives an error  -   "cannot find module 'ngx-cookie-service'"

**Comment by ankur-1989** [comment]
Review comments:- 

1. Help text for section "Available collections" need to be changed. The right content can be confirmed by Lisa.
2. For step 3, the next and skip buttons are not visible, So I cannot move to the next step. It goes to the end of the table. Need to fix this. 
![image](https://user-images.githubusercontent.com/24721077/61212713-58ea4780-a703-11e9-9de9-ff4c93d45018.png)
3. Content for the rest of the steps needs to be confirmed by Lisa.

**Comment by iamebuka** [comment]
@ankur-1989  I made correction for your second comment. For the other 2 I am looping @nguyenLisa for suggestions

**Comment by iamebuka** [comment]
Closing this issue now as the feature is merged to develop
