### ISSUE TITLE
If a User does not exist then on login with non-existing user should pop up customized error notification instead of browser default alert

### ISSUE THREAD

**Issue by ankur-1989** [ABenchM/abm-frontend#344]
**Describe the bug**
When a user login into the application with non-existing username then a customized message should be displayed instead of default alert.

**To Reproduce**
1. Go to 'Login page'.
2. Enter the details with the username that does not exist.
3. Click on Login button.
4. It will take you to the home page with alert pop up.

**Expected behavior**
 A customized message should be displayed saying "This user either does not exist or invalid".

**Comment by ankur-1989** [comment]
The reason for the pop error was as follows: 
 username entry was not present in the User table, but, was present in the role_members and role_properties table. Therefore, it allowed to log in.

If the entry for the username is not present in all the three tables: User, role, role_members 
Then it gives the following error on login - 
![image](https://user-images.githubusercontent.com/24721077/61236006-35d98b00-a737-11e9-9e8c-a7eab7d38437.png)

I have added one more feature - it will now show a message "Either username or password is invalid" as shown in the following figure:

![image](https://user-images.githubusercontent.com/24721077/61236137-9072e700-a737-11e9-8243-2cc30cb0f530.png)

@nguyenLisa Please confirm if this looks fine.

**Comment by nguyenLisa** [comment]
Please replace the message by "Invalid credentials". Then, feel free to merge. Thanks.

**Comment by ankur-1989** [comment]
closing this issue now. The solution is in prod now with the suggested changes.
