### ISSUE TITLE
Download link for the published collection is not visible at the available collection page.

### ISSUE THREAD

**Issue by ankur-1989** [ABenchM/abm-frontend#345]
**Describe the bug**
A reference to the published collection should be visible under Zenodo DOI reference header on the available collection page.

**Comment by ankur-1989** [comment]
Issue has been resolved and in production. @nguyenLisa Shall I close this issue now?

**Comment by nguyenLisa** [comment]
Sure, feel free to. Thanks for your work @ankur-1989

**Comment by ankur-1989** [comment]
closing this issue.
