### ISSUE TITLE
Add the filter option in show filtering option based on source.

### ISSUE THREAD

**Issue by ankur-1989** [ABenchM/abm-frontend#37]
As of now , when we search for a project on create collection page it shows limited number of collections on that page due to page limit. Therefore, filtering options should have option to search from the results on the basis of source suppose if user wants to select collection from a particular source such as Bitbucket instead of Github.

**Comment by mac24079** [comment]
@ankur-1989 
Little confused. 
Presently in the develop branch, when a user searches for a query there is no functionality that displays the project and the other details of that search. Should I implement this issue in the old ABM? like here : abm/bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/template

**Comment by ankur-1989** [comment]
yeah, search functionality in abm-frontend is not working as of now I am working on it. we have to implement it in abm-frontend only. By that time, you can start the design part, like, how are you going to show the filter options and what filter options are you going to show? I will let you know once this is done.

**Comment by mac24079** [comment]
Sounds good.

**Comment by mac24079** [comment]
Presently, when a user hits a query in search tab for e.g. "JAVA", the list of projects appear in an unordered manner. With respect to the key-filtereing option, the list of projects should appear first by the newest "collection date" of projects and then the user can use filtering functionality if needed.

**Comment by mac24079** [comment]
@ankur-1989 
As we are implementing many filter conditions under the "Show filtering" option on Create Collection page. I spoke with @nguyenLisa last week and decided to implement this directly under the "show filtering" component. I hope this will be fine. Kindly let me know if I am missing something important here.
Thanks.

**Comment by vishaljcj** [comment]
As discussed, this will be done with #248 . Hence closing this issue
