### ISSUE TITLE
Add functionality to search "Public Collections" on the Collection page so that user can see all the list of collections after their first search

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#41]
On collection's page list of default collections is available like Java, Junit, etc. If a user searches for Junit collection and type Junit in the search tab, the list containing Junit collections are appearing which is fine but there is no option for the user to go back to see those previous collections which were displaying before the search an user attempted. They are only allowed if they reload the page which is not a good practice. The functionality can be further enhanced so that if the user erases the word he/she typed, they should be allowed to see the list as before.

**Comment by ankur-1989** [comment]
This has been implemented and pushed to develop branch of abm-frontend repository. please feel free to test this functionality and let me know if you find any issue.

Now, we have given a cancel button, so once u are done with search either just press enter or by click on the button you can get the entire results back.

**Comment by mac24079** [comment]
Functionality described above is working fine. Thanks.

**Comment by ankur-1989** [comment]
ok closing the issue then.
