### ISSUE TITLE
Replace the current tab icon with ABM logo

### ISSUE THREAD

**Issue by 24santoshr** [ABenchM/abm-frontend#43]
Similar to the old ABM screen, the current tab icon can be changed to reflect ABM logo.

**Comment by nguyenLisa** [comment]
This issue is included in #32. Please edit it to specify your concern and close this issue.

**Comment by 24santoshr** [comment]
referenced in #32 . Hence closing this issue.

**Comment by 24santoshr** [comment]
@nguyenLisa  Can I pick this up and send the pull request once done?

**Comment by nguyenLisa** [comment]
Sure, please do :)
