### ISSUE TITLE
Add Hint/Tooltip for Affiliation field

### ISSUE THREAD

**Issue by ishwaryaPaderborn** [ABenchM/abm-frontend#44]
A normal user may not understand what to enter in the field 'Affiliation' in Registration page. So we could provide a hint/tooltip that will ease the user to understand what has to be filled in.

**Comment by mac24079** [comment]
Merged with https://github.com/ABenchM/abm-frontend/pull/109.
Hence, closing this ticket.

**Comment by mac24079** [comment]
Placeholder text to be kept as same as said in #7 .

Text - "Company / University / Institution" .

@nguyenLisa 
the text is sufficient above or

Text - "Company / University / Institution belongs to ..."

**Comment by mac24079** [comment]
Merged in https://github.com/ABenchM/abm-frontend/pull/204.

Hence, closing.
