### ISSUE TITLE
Create Collections page should redirect to a fresh page once the collection has been created.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#46]
Presently, when a collection is created by a user and in the same session if he/she hits back to search for a new collection, then the details (like projects selected) of the last collection created is displayed. It would be better if the page re-directs to a fresh page displaying the recent collection created in that session.
The figure shows the page that appear first after the creation of the collection by the user on the "Create Collections Page".
![reference_1](https://user-images.githubusercontent.com/23357897/40792136-782d45c2-64f9-11e8-81d3-b936118c4cbc.png)

**Comment by nguyenLisa** [comment]
This has already been reported in the issue tracker. Please check which issue this is about and close this one.

**Comment by mac24079** [comment]
Issue opened in repository: [https://github.com/ABenchM/abm/issues/103](url)
