### ISSUE TITLE
Fix issues reported by checkstyle

### ISSUE THREAD

**Issue by nguyenLisa** [ABenchM/abm-frontend#47]

**Comment by anut347** [comment]
Java: https://github.com/ABenchM/abm/pull/156
CSS: https://github.com/ABenchM/abm-frontend/pull/55
TypeScript: https://github.com/ABenchM/abm-frontend/pull/54
HTML: WIP

**Comment by anut347** [comment]
Keeping this issue open since html style check is not yet in place.

**Comment by mac24079** [comment]
Merged with https://github.com/ABenchM/abm-frontend/pull/282.

Hence, closing.
