### ISSUE TITLE
Issue with login with google account(was working last week)

### ISSUE THREAD

**Issue by anut347** [ABenchM/abm-frontend#49]
Login with google account feature which was working last week is not working now. And an invalid error message is shown  even when the google credentials were proper: 'Error: Wrong username or password.'

**Comment by nguyenLisa** [comment]
Can you identify the commit that introduced the error?

**Comment by mac24079** [comment]
@anut347 
Which branch did you test? I tested my functionalities on develop branch and it's working. Maybe after verifying you can close this one.

**Comment by mac24079** [comment]
Working fine. Hence, closing this ticket.

**Comment by nguyenLisa** [comment]
Thanks for looking into that @mac24079
