### ISSUE TITLE
Inconsistent behavior in Navigation bar page highlighting 

### ISSUE THREAD

**Issue by ishwaryaPaderborn** [ABenchM/abm-frontend#52]
When we navigate to a page initially the Navigation bar highlights the page with blue color. But if we click anywhere within the page the highlightining disappears.

**Comment by nguyenLisa** [comment]
This does not happen for me. Could you provide a screenshot and steps to reproduce?

**Comment by ishwaryaPaderborn** [comment]
Initial page view
![screenshot from 2018-06-04 23-34-49](https://user-images.githubusercontent.com/34371611/40942991-002fdef4-6850-11e8-96a3-e147247bea99.png)

After clicking anywhere within the page
![screenshot from 2018-06-04 23-35-02](https://user-images.githubusercontent.com/34371611/40943018-156b99ca-6850-11e8-9db3-3a90e5c24e67.png)

**Comment by nguyenLisa** [comment]
Could reproduce. Thanks for reporting!

**Comment by ankur-1989** [comment]
This issue has been fixed and pushed to branch collection as of now. For reference CommitId#  is 60bf9e15103a7b820e930d01951188397a7149ca.

You can check and close this ticket.
