### ISSUE TITLE
Creation of Admin page

### ISSUE THREAD

**Issue by ankur-1989** [ABenchM/abm-frontend#53]
We need an admin page which should only be visible to admin users. Following options should be available on this page.
1. Manage User Accounts
2. Manage User Collections

Under "Manage User accounts" view, a user should be able to modify the roles of user, delete the user account etc.

Under "Manage User Collections" view, a user should be able to delete the collection of any user, should be able to see the collections created by a particular user and edit them.

**Comment by mac24079** [comment]
I would be interested in taking this.
Should the page appear after the user log in the application and there he can manage all the services you mentioned above?
If yes I can first create a small prototype and upload here to not mix-up wrong things.

**Comment by mac24079** [comment]
@nguyenLisa 
As we spoke today, I searched the internet and didn't find the exact information that whether we can delete a user account or not. 
But I surfed the internet and get to know we can deactivate a user but can not delete the user account and their profile. But sadly didn't found any concrete references.

**Comment by vishaljcj** [comment]
done and merged with develop.
