### ISSUE TITLE
Incorrect highlight of the tab in navigation bar, while clicking on the ABM logo

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#56]
Clicking on the ABM logo redirects to the home page, but the highlighted tab in the main navigation bar still remains on the previous page, from which the click was performed.

**Comment by nguyenLisa** [comment]
Please merge this with #52

**Comment by ankur-1989** [comment]
Fixed the issue reference commit is 2b5c590ad04c93d78195fad4860415166b25a8c5
in develop branch.

**Comment by ankur-1989** [comment]
you can check once and close the ticket. Thanks
