### ISSUE TITLE
Integrate "Angular material" with abm-frontend

### ISSUE THREAD

**Issue by Chinmay-92** [ABenchM/abm-frontend#57]
Integration of angular material 6.2.1 to abm-frontend.
Link :- https://material.angular.io/

**Comment by nguyenLisa** [comment]
Why is this needed?

**Comment by ishwaryaPaderborn** [comment]
As our team had propsed in the Architecture Homework last week to integrate 'Angular Material' for ABM frontend and when discussed with you we understood that we need to create an issue for the same, so as to decide if the integration is scalable or not.

**Comment by nguyenLisa** [comment]
In this case, please create an issue with the feature(s) you want to add, and mention the material integration in the issue's description. Please understand that integrating Angular Material for the purpose of integrating Angular Material should not be done.
