### ISSUE TITLE
Inconsistent behavior on error messages of password field on Registration page 

### ISSUE THREAD

**Issue by Chinmay-92** [ABenchM/abm-frontend#58]
On the registration page,
Password required error is not coming when user just clicks on the "password" and "confirm password" input fields and without entering anything moves to next input fields. ( only red border will be applied to input field )
Expected behavior : same as username field error scenario ( it should show error message immediately when you touch that input field ) 
![error_messages](https://user-images.githubusercontent.com/2173927/41424632-e2f16360-6ffe-11e8-876f-4f88d8a49d1e.png)

**Comment by ankur-1989** [comment]
Fix for this issue is on GitHub now. We can close this issue.

**Comment by ankur-1989** [comment]
as this has been fixed and live on develop branch, therefore, closing this issue.
