### ISSUE TITLE
Hovering over the ABM logo should change the appearance of the mouse pointer

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm-frontend#63]
Currently, the user is redirected to the homepage when he/she clicks on the ABM logo. But an end-user with no knowledge of ABM whatsoever, would not be able to interpret the logo as click-able, since the ordinary mouse pointer is used here, which makes no clear distinction between the non functional elements within the page. This should be replaced by ,for e.g. some hand-pointer, which is the standard used in most places nowadays, so that the user would be able to easily identify that this logo , in fact, can be clicked.

**Comment by ankur-1989** [comment]
I have already fixed this issue. will commit by tonight in develop branch.

**Comment by ankur-1989** [comment]
Pushed the change to develop branch. closing this issue.
