### ISSUE TITLE
The list of projects(table) should appear first in an alphabetical order on "Create Collections" page.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#65]
Presently, when a user hits a query in search tab for e.g. "JAVA", the list of projects appear in an unordered manner. There is also a functionality that the user can click on the "Name" column but that too is not working in a proper way(in old ABM). 
Since we already opened an issue #37 for adding filters to the table, I would suggest the list of projects should appear first either in an "alphabetical way" or by the newest "collection date" of projects and over that the filtering option will be the cream part for the users if they want to use that.

**Comment by mac24079** [comment]
@nguyenLisa @ankur-1989 
I and @janniclas were discussing this and would like to have the opinion whether should we keep this open or merge this with issue #37 ?

**Comment by nguyenLisa** [comment]
Please merge with #37  and add the information that by default, the projects should be ordered by update date.

**Comment by mac24079** [comment]
Merged with issue #37 .
