### ISSUE TITLE
There is a need to write a proper guide on how to use ABM

### ISSUE THREAD

**Issue by Ayybeeshafi** [ABenchM/abm-frontend#66]
There is a need to write down a proper guide on how to use ABM for new users.
For users assistance there should be a section of How to and FAQs.
Existing information is incomplete.
![image](https://user-images.githubusercontent.com/34144308/41568829-4d236096-7368-11e8-85b9-dc1ac9411e08.png)

**Comment by nguyenLisa** [comment]
If the UI is good enough, there should be little need for such documentation. But indeed, having one doesn't hurt. Good catch!

**Comment by mac24079** [comment]
@nguyenLisa  That's correct.
Though it's the UI, I would also like to suggest about adding more information to the Wiki pages to the repositories for the application, as there is not much at the present.

P.S. If as a developer I look for information on some repositories, I search the Wiki pages most of the time.

**Comment by iamebuka** [comment]
@nguyenLisa Trying to push my commits on this issue, but it shows I don't have permissions to do that. Could something be done about it?

**Comment by nguyenLisa** [comment]
Hi @iamebuka ,

Which branch are you trying to push to? Master and develop are protected, so you should create your own branch from develop, do your changes there, and issue a pull request to develop.

Cheers,
Lisa

**Comment by iamebuka** [comment]
@nguyenLisa can I go ahead and close this issue as it has been solved?

**Comment by nguyenLisa** [comment]
Sure, please do.

**Comment by iamebuka** [comment]
The issue has been resolved and changes merged to the develop branch
