### ISSUE TITLE
New version of the Login Page/Landing Page for ABM application.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#67]
At present, we have a very simple first landing page of the application where the user is able to see only a few things. We can enhance that by adding some more aesthetics to it. Below I am attaching a picture that shows both the existing and new proposed version respectively.
![reference](https://user-images.githubusercontent.com/23357897/41661032-fc596be2-749d-11e8-95e0-588a613785a8.jpg)

**Comment by mac24079** [comment]
@nguyenLisa 
We spoke about this in the starting weeks of the PG meetings.
Here I am also attaching the pdf file made by Balsamiq prototype, in case one wants to look for the functionalities. 
[new_version.pdf](https://github.com/ABenchM/abm-frontend/files/2119501/new_version.pdf)

**Comment by nguyenLisa** [comment]
Thanks for opening up this issue. But as far as I am concerned, this is not the final version of the application's UI. Please re-discuss this with the entire group and upload a new version only when it has been agreed upon with us.

**Comment by mac24079** [comment]
Yeah, I'll do that.

**Comment by mac24079** [comment]
This is the final version discussed with the group. We are planning to start working on this in the upcoming weeks, so would like to have your final suggestions/comments as feedback.

![image](https://user-images.githubusercontent.com/23357897/43392597-70727daa-93f4-11e8-85eb-fcd7aa6d2186.png)

**Comment by nguyenLisa** [comment]
Let's go with that. We'll do some adjustments later.
