### ISSUE TITLE
Implement the filter option in My collections table list.

### ISSUE THREAD

**Issue by ankur-1989** [ABenchM/abm-frontend#68]
![image](https://user-images.githubusercontent.com/24721077/42125186-00cd9b5e-7c72-11e8-9d0a-3e403fe2d760.png)

As of now, we are getting a complete list of user collections created by that particular user. As part of this issue, a filter option need to apply so that user can see only built collections or any other criteria that user wants to apply. 

For Reference :- 

![image](https://user-images.githubusercontent.com/24721077/42125212-9fa5d836-7c72-11e8-82b5-138ac6c0001f.png)

Like this, we can give option to toggle the filter on the page or if you think any other best option insead of this.

**Comment by mac24079** [comment]
@ankur-1989 
I looked into this, the reference given here corresponds to grid options but here in the new application, we are using normal tables instead of Grid options. Should we use grid options to give the same UI or provide search bar to filter the table according to given query?

**Comment by ankur-1989** [comment]
![image](https://user-images.githubusercontent.com/24721077/42134656-8d17b256-7d40-11e8-8d5d-7a8200f7f6d4.png)

or you can try like this , by this along with search, we can limit the number of entries that need to be displayed at a time.

**Comment by ankur-1989** [comment]
Implemented by Issue#95. therefore this issue is not needed anymore. closing this issue.
