### ISSUE TITLE
Implement the Hermes progress modal window similar to Build progress modal window 

### ISSUE THREAD

**Issue by ankur-1989** [ABenchM/abm-frontend#69]
In our current application, when we build a collection then this opens a modal window showing the progress at each stage.

![image](https://user-images.githubusercontent.com/24721077/42125263-c425a0d2-7c73-11e8-8f1c-ef0f3fcb8849.png)

Likewise, as part of this issue, we need to implement the similar modal window when we are running Hermes on Built collection. 

This issue is part of both front end and back end as it requires code change at both ends.

**Comment by ankur-1989** [comment]
Hi Team,

Any Update on this issue?

Thanks!!

**Comment by vishaljcj** [comment]
This is not required in ABM anymore as it will be handled in delphi
