### ISSUE TITLE
Adding a new Profile Page that can be used for editing the profile details of a user.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#7]
Presently, once a user login he/she is unable to change their login details like info, password and picture(optional) as there is no page available that links the user to update/modify their details.
![reference](https://user-images.githubusercontent.com/23357897/40266612-03f288ba-5b4f-11e8-9402-915268c7676a.png)

**Comment by mac24079** [comment]
@nguyenLisa 
This is the final version discussed with the group and also what we kept in our design document of the PG. Any remarks on the below attached prototype? As said by you in #67 , we can make adjustments to it later on.
Thanks


![image](https://user-images.githubusercontent.com/23357897/43397800-4e79c656-9406-11e8-9409-7968cf7bdc96.png)

**Comment by nguyenLisa** [comment]
Let's go for that one, we'll adjust later. One thing though: the round pencil icons are not needed.

**Comment by mac24079** [comment]
Yeah they won't be there.

**Comment by mac24079** [comment]
**@nguyenLisa** 
Need opinions on this design!! The functionalities like checking for password matching, user_name on the top, blank enteries not allowed will be present and I removed the "Change password option " heading as mentioned in the prototype because it was giving a somehow different look to the actual page. Functionality is working for the page but the test cases are not done at the moment and also to avoid multiple merge requests I thought to write here first.

![image](https://user-images.githubusercontent.com/23357897/43452889-d973ea0e-94b8-11e8-9c09-5de9634bc244.png)

**Comment by nguyenLisa** [comment]
- The grey text in "Email" should provide an example email, with @ and .
- Check the English for the grey text in "Affiliation"
- Retype password: which one, old or new?
- Is the password (old + new + retype) necessary for changing the email address or the username? This is not obvious in the design.
- "Be careful..." should be next to or above the Delete account button, not below.

**Comment by mac24079** [comment]
Thanks for the feedback. Comments point by point:

- Do you mean like this?
xyz@gmail.com 
if yes, can I use the same as above in the Placeholder?

- Corrected as:
" **Organization/Institution belongs to...** " this is what I added to issue #44 previously. Kindly let me know in the case it needs to be rechanged.

- Corrected as "Confirm New Password"

- Yes it is. User must type the current password and then proceed for the next enteries. In case the user doesn't write the old password the fields won't allow the user to write anything in the New password and re-type password. Also, in case the old password and new+confirm password doesn't match an alert will appear for the same.

- My bad, it should be above. I have corrected that.

![image](https://user-images.githubusercontent.com/23357897/43479368-8c09ba08-9500-11e8-9479-86d6a527f542.png)

**Comment by nguyenLisa** [comment]
- Yes. Yes.
- Company / University / Institution
- Thanks.
- What I meant is that there are three situations where the design is unclear: 
  - If I want to change my username, it looks like I need to enter a new password, which should not be the case. 
  - If I want to change my email address, it looks like my username is not populated by default, so what happens? Should I enter it again? Or if I don't enter it, is it reset to empty?
  - If I want to change my password, do I also need to enter my username, email and the other information?
- Thanks.

**Comment by mac24079** [comment]
I got the concern. Will make them clear in the next part.

**Comment by mac24079** [comment]
Response to points which were unclear above:

- Yes that would not be the case. Kindly refer to the figure attached.

- **Does this answer your question?**
By default the details of the user would be there and when a user wants to change the e-mail address, the username with which the user is registered will be there by default. The editing in the form will be dynamic i.e. what the user wants to change, can change but must hit the Save changes button. There is no dependency releated to any element in the form except Changing the password scenario.

- No.

![image](https://user-images.githubusercontent.com/23357897/43990617-f7db6b9a-9d5d-11e8-9e38-f909fb603184.png)

**Comment by mac24079** [comment]
**Update:**
The data is populated automatically for the first five fields/columns, so no placeholder text for those fields.

**Comment by mac24079** [comment]
Merged with https://github.com/ABenchM/abm-frontend/pull/276.

Hence, closing.
