### ISSUE TITLE
Alignment needs to be fixed when searching in Create Collection Page 

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm-frontend#71]
At present, when a user searches for some project like **Java** in this case, the details appearing in the table seems to be not aligned properly.
![ref](https://user-images.githubusercontent.com/23357897/42178429-a3f21714-7e30-11e8-880d-14e466b72f27.png)

**Comment by mac24079** [comment]
@nguyenLisa @ankur-1989 
Is this alignment is fine(below)? if yes, I would like to keep the same formatting for the Collection page as well. Kindly let me know.
![screenshot from 2018-07-08 17-36-28](https://user-images.githubusercontent.com/23357897/42421457-30ec8718-82d6-11e8-8aec-566e91e49793.png)

Thanks.

**Comment by ankur-1989** [comment]
@mac24079 please align the show filtering options button with search button as it was earlier.

**Comment by mac24079** [comment]
yeah sure, thanks for writing.

**Comment by mac24079** [comment]
@ankur-1989 
I checked the point you mentioned for making the alignment for the search button as before means **Show filtering options** just next to the search button. For this I checked but it is some other issue I guess as to fix this I cloned the abm-frontend repo again to my system as I was unable to detect the wrong alignment in my code. 
Can you please check this once?

Thanks.

**Comment by mac24079** [comment]
Completed. Hence, closing.
![reference](https://user-images.githubusercontent.com/23357897/43384016-04be0b4a-93dd-11e8-98e9-3c73415f2b71.png)
