### ISSUE TITLE
Spelling and sentence structure mistake in feedback displayed once user is registered.

### ISSUE THREAD

**Issue by Ayybeeshafi** [ABenchM/abm-frontend#8]
''You will be* able to log in.''
In the second sentence, I think "This should take no longer than a working day." is a proper sentence as compared to "work day".
![image](https://user-images.githubusercontent.com/34144308/40288011-8eb17f8e-5cb1-11e8-84c2-ef33f31ef25e.png)

**Comment by ankur-1989** [comment]
Fixed in abm-front end  and abm repository both. pushed to develop branch 70f0cf57e25a0fe5fba9e56cdcf25a8bd09dafc7 for abm-frontend 
f3b443fb84ec5c20bf9076ac0140f86a412cd6b2 for abm
Therefore, closing this issue.
