### ISSUE TITLE
Clicking on  project should open the corresponding source repository

### ISSUE THREAD

**Issue by janniclas** [ABenchM/abm-frontend#9]
When selecting projects to create a collection, users should be able to open the project on the corresponding source repository (e.g Github) to get a better insight of the project.
This will help the users to make a decision if they want to add that specific project to their collection.

Currently the collection view is not implemented in the new abm-frontend, but this feature request should still be valid once the collection view has been fully implemented. 

![image](https://user-images.githubusercontent.com/8062521/40301019-0fc25ad8-5ceb-11e8-9e5d-dcc294487cac.png)

Issue originates from: https://github.com/ABenchM/abm/issues/131

**Comment by ankur-1989** [comment]
Do we really need this feature? if we are going to apply the filters before and after getting the projects which makes sure on which project we are working on and can determine the features of that project in our application itself.

**Comment by nguyenLisa** [comment]
I'm not sure I get your point. I think that what is suggested makes sense: on click on a project, it is convenient to be able to nagivate to the original source of where we got the code, regardless of which filters we already ran or not. Could you clarify what you meant @ankur-1989 ?

**Comment by ankur-1989** [comment]
However, this would be a nice feature, but, I was under the impression that the goal of this application is to make benchmarking of projects automatic. If I have to manually scan the GitHub source and then decide if I have to take this project or not then it will take a lot of time. What I wanted to say that Our application should less with all those functionalities which could decide itself which projects should come into a collection based on filters.  Please suggest.

**Comment by nguyenLisa** [comment]
The goal of this feature is not to allow you to manually scan the source. We should make it transparent to users where we get the sources from. If not from there, then from somewhere else. In any case, this feature should be in there. I don't think it should be that hard to implement, and it makes a lot of sense w.r.t. what users expect from this type of UIs.

**Comment by ankur-1989** [comment]
Sure. I'll include this.

**Comment by ankur-1989** [comment]
Implementation is done. As of now, I am opening the source into a new tab. Is this fine?  or Should I open in the same tab?

**Comment by nguyenLisa** [comment]
The new tab is fine. Thanks!

**Comment by ankur-1989** [comment]
Sure. I'll push the changes to develop branch and keep this issue open for testing.

**Comment by ankur-1989** [comment]
closing this issue. can be reopened if somebody finds an issue.
